const gateway_v = exports.gateway_v = 6;
const api = exports.api = `https://discordapp.com/api/v${gateway_v}`;
const Endpoints = exports.endpoints = {
    login: `${api}/auth/login`,
    logout: `${api}/auth/logout`,
    gateway: `${api}/gateway`,
    botGateway: `${api}/gateway/bot`,
    invite: (id) => `${api}/invite/${id}`,
    inviteLink: (id) => `https://discord.gg/${id}`,
    CDN: 'https://cdn.discordapp.com',
    user: (userID) => `${api}/users/${userID}`,
    userChannels: (userID) => `${Endpoints.user(userID)}/channels`,
    userProfile: (userID) => `${Endpoints.user(userID)}/profile`,
    avatar: (userID, avatar) => userID === '1' ? avatar : `${Endpoints.user(userID)}/avatars/${avatar}.jpg`,
    me: `${api}/users/@me`,
    meGuild: (guildID) => `${Endpoints.me}/guilds/${guildID}`,
    relationships: (userID) => `${Endpoints.user(userID)}/relationships`,
    channel: (channelID) => `${Endpoints.channels}/${channelID}`,
    channelMessages: (channelID) => `${Endpoints.channel(channelID)}/messages`,
    channelInvites: (channelID) => `${Endpoints.channel(channelID)}/invites`,
    channelTyping: (channelID) => `${Endpoints.channel(channelID)}/typing`,
    channelPermissions: (channelID) => `${Endpoints.channel(channelID)}/permissions`,
    channelMessage: (channelID, messageID) => `${Endpoints.channelMessages(channelID)}/${messageID}`,
    channelWebhooks: (channelID) => `${Endpoints.channel(channelID)}/webhooks`,
    guild: (guildID) => `${Endpoints.guilds}/${guildID}`,
    guildIcon: (guildID, hash) => `${Endpoints.guild(guildID)}/icons/${hash}.jpg`,
    guildPrune: (guildID) => `${Endpoints.guild(guildID)}/prune`,
    guildEmbed: (guildID) => `${Endpoints.guild(guildID)}/embed`,
    guildInvites: (guildID) => `${Endpoints.guild(guildID)}/invites`,
    guildRoles: (guildID) => `${Endpoints.guild(guildID)}/roles`,
    guildRole: (guildID, roleID) => `${Endpoints.guildRoles(guildID)}/${roleID}`,
    guildBans: (guildID) => `${Endpoints.guild(guildID)}/bans`,
    guildIntegrations: (guildID) => `${Endpoints.guild(guildID)}/integrations`,
    guildMembers: (guildID) => `${Endpoints.guild(guildID)}/members`,
    guildMember: (guildID, memberID) => `${Endpoints.guildMembers(guildID)}/${memberID}`,
    stupidInconsistentGuildEndpoint: (guildID) => `${Endpoints.guildMember(guildID, '@me')}/nick`,
    guildChannels: (guildID) => `${Endpoints.guild(guildID)}/channels`,
    guildEmojis: (guildID) => `${Endpoints.guild(guildID)}/emojis`,
    webhook: (webhookID, token) => `${api}/webhooks/${webhookID}${token ? `/${token}` : ''}`,
};
